name: AutoBuild

#
# Constructed with help from:
# - https://blog.logrocket.com/android-ci-cd-using-github-actions/
# - https://www.droidcon.com/2022/01/05/getting-started-ci-cd-for-android-project-part-3-github-actions/
# - https://stackoverflow.com/questions/61335109/
# - https://github.com/actions/setup-java
# - https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
#

on:
  release:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: JDK 17 Set Up
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle Build
        run: ./gradlew build --no-daemon
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build_Outputs
          path: app/build/outputs
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
